insert into estados (nome, descricao)
VALUES ('AC', 'Acre'),
        ('AL', 'Alagoas'),
        ('AP', 'Amapá'),
        ('AM','Amazonas'),
        ('BA','Bahia'),
        ('CE','Ceara'),
        ('DF','Distrito Federal'),
        ('ES', 'Espirito Santo'),
        ('GO', 'Goias'),
        ('MA','Maranhao'),
        ('MT','Mato Grosso'),
        ('MS','Mato Grosso do Sul'),
        ('MG','Minas Gerias'),
        ('PA','Para'),
        ('PB','Paraiba'),
        ('PR','Parana'),
        ('PE','Pernambuco'),
        ('PI','Piaui'),
        ('RJ','Rio de Janeiro'),
        ('RN','Rio Grande do Norte'),
        ('RS','Rio Grande do Sul'),
        ('RO','Rondonia'),
        ('RR','Roraima'),
        ('SC','Santa Catarina'),
        ('SP','São Paulo'),
        ('SE','Sergipe'),
        ('TO','Tocantins');
select * from estados;